image: python:3.9

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - build

.install-deps-template: &install-deps
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv --no-dev

build:
  <<: *install-deps
  stage: build
  script:
    - poetry build -n
    - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry publish -r gitlab
