aws_region: af-south-1
instance_type: g4dn.xlarge
instance_ami: ami-0a636d96511f61b74
volume_size: 200
sync_paths:
  - ./
  - ~/.aws
project_id: some-project-identifier
credentials_profile_name: playground
bind_address: "0.0.0.0"
ignore_dirs:
  - .venv
  - .git
  - node_modules
  - __pycache__
  - diffusers-cache
local_port_forwards:
  user-api:
    "2020": "2020"
  blog-api:
    "3030": "3030"
