sync_paths:
  - ./
  - ~/.aws
project_id: some-project-identifier
credentials_profile_name: playground
bind_address: "0.0.0.0"
ignore_dirs:
  - .venv
  - .git
  - node_modules
  - __pycache__
  - diffusers-cache
local_port_forwards:
  user-api:
    "2020": "2020"
  blog-api:
    "3030": "3030"
instance_config_path: ./perry_instance_config.json