aws_region: af-south-1
instance_type: t3.large
volume_size: 100
sync_dir: ./
project_id: "some-project-id"
ignore_dirs:
  - .venv
  - .git
  - node_modules
  - __pycache__
remote_port_forwards:
  local-webpack-app:
    "8080": "8080"
local_port_forwards:
  user-api:
    "2020": "2020"
  blog-api:
    "3030": "3030"
